"""
adversarial_generator.py — Adversarial Query Generator & Self-Improving Loop

This module introduces a genetic algorithm that competes against the SQL debugging 
agent. It takes structurally correct queries and injects increasingly complex 
bugs (mutations) to try and "defeat" the debugging agent.

The Generator's fitness score is inversely proportional to the Agent's success:
If the agent easily solves the bug, the mutant dies. If the agent fails or times out,
the mutant survives to the next generation and is mutated further. 

Run this to output metrics comparing Generator Complexity vs Debugger Success Rate.
"""

import re
import random
import logging
import time
from copy import deepcopy

# Import isolated backend components
from multi_step_env import MultiStepSQLEnv
from dynamic_schema import DynamicSQLEnv, generate_random_schema
from hybrid_agent import HybridAgent
from models import TaskInfo

logger = logging.getLogger(__name__)


# =============================================================================
# Malicious Environment Injection 
# =============================================================================

class AdversarialSQLEnv(DynamicSQLEnv):
    """
    Subclass of DynamicSQLEnv that bypasses random task generation 
    and forces the environment to use an adversarially generated broken query.
    """
    def __init__(self, malicious_task: TaskInfo):
        super().__init__()
        self._malicious_task = malicious_task
        
    def _load_task(self, task_id: str, scenario: str = None) -> TaskInfo:
        # Instead of dynamically generating a random broken query, 
        # we inject the mutant generated by the Genetic Algorithm.
        return self._malicious_task


# =============================================================================
# SQL Mutator (Genetic Operators)
# =============================================================================

class SQLMutator:
    """Applies realistic logical and syntactic bugs to correct SQL queries."""
    
    @staticmethod
    def mutate_off_by_one(sql: str) -> str:
        """Injects off-by-one logical errors in comparison operators."""
        mutations = [
            (" > ", " >= "),
            (" < ", " <= "),
            (" >= ", " > "),
            (" <= ", " < "),
            (" = ", " != ")
        ]
        random.shuffle(mutations)
        for orig, mut in mutations:
            if orig in sql:
                return sql.replace(orig, mut, 1)
        return sql

    @staticmethod
    def mutate_drop_condition(sql: str) -> str:
        """Removes a WHERE condition entirely, leading to over-fetching."""
        # Simple regex to rip out basic WHERE clauses
        mutated = re.sub(r'WHERE\s+.*?(ORDER BY|GROUP BY|LIMIT|$)', r'\1', sql, flags=re.IGNORECASE)
        # If no change occurred, try dropping an AND condition
        if mutated == sql:
            mutated = re.sub(r'\s+AND\s+.*?(ORDER BY|GROUP BY|LIMIT|$)', r' \1', sql, flags=re.IGNORECASE)
        return mutated

    @staticmethod
    def mutate_swap_logic(sql: str) -> str:
        """Swaps AND / OR logic to create subtle data leak / constraint bugs."""
        if " AND " in sql.upper():
            return re.sub(r'\s+AND\s+', ' OR ', sql, count=1, flags=re.IGNORECASE)
        elif " OR " in sql.upper():
            return re.sub(r'\s+OR\s+', ' AND ', sql, count=1, flags=re.IGNORECASE)
        return sql
    
    @staticmethod
    def mutate_break_join(sql: str) -> str:
        """Breaks a JOIN by removing the ON condition, causing a Cartesian product."""
        # e.g. JOIN users ON users.id = orders.user_id -> JOIN users
        return re.sub(r'JOIN\s+(\w+)\s+ON\s+[\w\.]+\s*=\s*[\w\.]+', r'JOIN \1', sql, count=1, flags=re.IGNORECASE)

    @classmethod
    def apply_random_mutation(cls, sql: str) -> str:
        """Randomly apply one genetic mutation to a query."""
        operators = [
            cls.mutate_off_by_one,
            cls.mutate_drop_condition,
            cls.mutate_swap_logic,
            cls.mutate_break_join
        ]
        
        # Try finding a mutation that actually changes the string
        random.shuffle(operators)
        for op in operators:
            mutated = op(sql)
            if mutated != sql:
                return mutated
                
        # Fallback: just add a syntax error
        return sql + " SYNTAX_ERROR"


# =============================================================================
# Genetic Algorithm Loop
# =============================================================================

class GeneticAdversary:
    """
    Manages the evolutionary loop: evaluating mutants against the current agent, 
    culling weak bugs (easily solved), and evolving strong bugs (failures).
    """
    def __init__(self, agent: HybridAgent, population_size=5):
        self.agent = agent
        self.population_size = population_size
        self.metrics_log = []
        
    def _evaluate_mutant(self, mutant_task: TaskInfo, max_steps=10) -> float:
        """
        Runs the LLM Agent against the malicious task. 
        Returns fitness score for the generator (Higher = Generator Beat the Agent).
        """
        # Inject the mutant task into our isolated environment
        base_env = AdversarialSQLEnv(malicious_task=mutant_task)
        env = MultiStepSQLEnv(base_env, max_steps=max_steps)
        
        obs, info = env.reset()
        if type(obs) == tuple: # API compat sync
            obs = obs[0]
            
        done = False
        step_count = 0
        final_reward = 0.0
        
        # Agent debugging loop
        while not done and step_count < max_steps:
            action = self.agent.get_action(obs)
            
            result = env.step(action)
            if len(result) == 5:
                next_obs, reward, done, truncated, info = result
                done = done or truncated
            else:
                next_obs, reward, done, info = result
                
            obs = next_obs
            final_reward += reward
            step_count += 1
            
        # FITNESS CALCULATION:
        # If agent solves it quickly, fitness is LOW.
        # If agent times out or fails, fitness is HIGH.
        success = (info.get("reward", 0) >= 1.0) or ("Success" in info.get("feedback", ""))
        
        if success:
            return -1.0 + (step_count * 0.05) # Solved, but penalize generator less if it took many steps
        else:
            return 1.0 # Generator successfully defeated the agent!

    def generate_seed_population(self) -> list[TaskInfo]:
        """Creates the initial population by dynamically generating schemas and valid baseline tasks."""
        population = []
        for _ in range(self.population_size):
            db_path, schema_str, tables = generate_random_schema(num_tables=(2, 3))
            target_table = tables[0]["name"]
            
            if len(tables[0]["columns"]) > 1:
                col = tables[0]["columns"][1]["name"]
            else:
                col = "id"
                
            # Create a valid source of truth query
            correct_query = f"SELECT {col} FROM {target_table} WHERE id > 0 ORDER BY id LIMIT 5"
            
            # Exec against DB to get expected output target
            import sqlite3
            conn = sqlite3.connect(db_path)
            cursor = conn.execute(correct_query)
            expected_output = [dict(zip([c[0] for c in cursor.description], row)) for row in cursor.fetchall()]
            conn.close()
            
            # Apply initial mutation
            mutant_query = SQLMutator.apply_random_mutation(correct_query)
            
            task = TaskInfo(
                task_id="adversarial_seed",
                broken_query=mutant_query,
                schema_sql=schema_str,
                expected_output=expected_output,
                db_path=db_path
            )
            
            # Store the correct query if we needed it (not needed for mutation)
            population.append(task)
            
        return population

    def train_loop(self, epochs=5):
        """Main training cycle: generate, evaluate, and evolve."""
        logger.info(f"Starting Adversarial Evolution for {epochs} epochs...")
        population = self.generate_seed_population()
        
        for epoch in range(epochs):
            logger.info(f"\n--- Epoch {epoch+1} ---")
            
            epoch_fitness = []
            success_count = 0
            
            for i, mutant in enumerate(population):
                fitness = self._evaluate_mutant(mutant)
                epoch_fitness.append((fitness, mutant))
                
                # If fitness < 0, the Agent won (Generator failed to defeat agent)
                if fitness < 0:
                    success_count += 1
                    
            # Sort by fitness descending (best mutants / hardest bugs first)
            epoch_fitness.sort(key=lambda x: x[0], reverse=True)
            
            agent_success_rate = success_count / self.population_size
            avg_mutant_fitness = sum(f[0] for f in epoch_fitness) / self.population_size
            
            self.metrics_log.append({
                "Epoch": epoch + 1,
                "Agent Success Rate": agent_success_rate,
                "Avg Mutant Complexity (Fitness)": avg_mutant_fitness
            })
            
            logger.info(f"Agent Success Rate: {agent_success_rate*100:.1f}% | Avg Mutant Fitness: {avg_mutant_fitness:.2f}")
            
            # Elitism: evolve the population for the next epoch
            survivors = [task for fit, task in epoch_fitness[:self.population_size // 2]]
            
            new_population = []
            new_population.extend(survivors)
            
            # Mutate survivors to replace the weak ones
            while len(new_population) < self.population_size:
                parent = random.choice(survivors)
                child = deepcopy(parent)
                
                # Apply an additional mutation on top of the already broken query
                child.broken_query = SQLMutator.apply_random_mutation(child.broken_query)
                new_population.append(child)
                
            population = new_population

        return self.metrics_log


# =============================================================================
# Execution Entry Point (Demonstration)
# =============================================================================
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    
    # Instantiate the target RL agent we are trying to defeat.
    # Note: Use a mock or local model to avoid OpenAI API costs during generator training loops
    target_agent = HybridAgent(model_name="mock_local", use_rl_finetune=False)
    
    generator = GeneticAdversary(agent=target_agent, population_size=4)
    metrics = generator.train_loop(epochs=3)
    
    print("\n--- Final Metrics (Generator Complexity vs Debugger Success) ---")
    for m in metrics:
        print(m)
